name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Your Sofia
title: '[Bug]: '
labels: ['bug', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please first check if it has already been reported.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Example - Map view not showing newly added city objects.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to recreate the bug
      placeholder: |
        1. Open the app
        2. Navigate to Map view
        3. Notice map does not show newly added city objects
      value: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Map view should show newly added city objects  immediately after they are added.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Map view does not show newly added city objects immediately after they are added.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: On which platform does this occur?
      options:
        - iOS
        - Android
        - Both iOS and Android
        - Web (backend admin panel)
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device Information
      description: Device model (e.g., iPhone 14 Pro, Samsung Galaxy S21)
      placeholder: iPhone 14 Pro
    validations:
      required: false

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: Operating system version (e.g., iOS 17.1, Android 14)
      placeholder: iOS 17.1
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: Version number from app settings/profile
      placeholder: '1.0.0'
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Messages or Logs
      description: Any error messages, stack traces, or console logs
      placeholder: Paste error messages here
      render: shell
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Videos
      description: Attach screenshots or screen recordings that show the bug
      placeholder: Drag and drop images or videos here
    validations:
      required: false
