name: 📖 Documentation Improvement
description: Suggest improvements to documentation, guides, or examples
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation helps everyone contribute to Your Sofia.

  - type: dropdown
    id: doc-area
    attributes:
      label: Documentation Area
      description: Which documentation needs improvement?
      options:
        - README (main project overview)
        - Contributing Guidelines
        - API Documentation
        - Setup/Installation Guide
        - Code Comments
        - Architecture Documentation
        - Translation Guide
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Issue
      description: What kind of documentation issue is this?
      options:
        - Missing Information
        - Incorrect/Outdated Information
        - Unclear/Confusing Explanation
        - Typo/Grammar Error
        - Needs More Examples
        - Translation Issue (Bulgarian/English)
        - Broken Links
        - Other
    validations:
      required: true

  - type: textarea
    id: current-docs
    attributes:
      label: Current Documentation
      description: What does the current documentation say? (Paste relevant section or provide link)
      placeholder: |
        Link: https://github.com/sofia-municipality/your-sofia/blob/main/README.md#section
        
        Current text:
        "To start the app, run npm start"
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: What's wrong or missing? Why is this confusing?
      placeholder: |
        The documentation says to use "npm start" but the project uses pnpm, not npm. This causes errors for new contributors who follow the documentation exactly.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be changed or improved?
      placeholder: |
        Change "npm start" to "pnpm dev" to match the actual package manager used.
        
        Also add a note at the beginning stating:
        "This project uses pnpm, not npm or yarn. Install it with: npm install -g pnpm"
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      description: Which language version needs updating?
      options:
        - English
        - Bulgarian
        - Both English and Bulgarian
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - This confusion was mentioned by multiple contributors in #123
        - Similar issue exists in the Contributing guide
    validations:
      required: false

  - type: checkboxes
    id: willing-to-fix
    attributes:
      label: Are you willing to submit a PR to fix this?
      description: Documentation PRs are great first contributions!
      options:
        - label: Yes, I'd like to update the documentation
