name: 💡 Feature Request
description: Suggest a new feature or enhancement for Your Sofia
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Your ideas help make Your Sofia better for all citizens of Sofia.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: This feature aligns with the project goals (citizen engagement, transparency, accessibility)
          required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which part of the app would this feature affect?
      options:
        - News & Notifications
        - City Services & Navigation
        - Civic Participation (Signals/Reports)
        - Maps & Location Services
        - User Profile & Settings
        - Backend/Admin Panel
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Why is it needed?
      placeholder: |
        Citizens are not notified when air quality reaches unhealthy levels, missing opportunities to protect their health and make informed decisions about outdoor activities.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would this feature work? Be as detailed as possible.
      placeholder: |
        Add push notifications when air quality index exceeds a user-defined threshold:
        - User sets threshold in Profile settings (e.g., "Notify when AQI > 100")
        - Backend checks air quality data every 30 minutes
        - If threshold exceeded, send push notification with:
          - Current AQI value
          - Health recommendations
          - Link to detailed air quality map
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you thought about?
      placeholder: |
        - In-app banner only (less effective, requires app to be open)
        - Email notifications (slower, less immediate)
        - SMS notifications (expensive, privacy concerns)
    validations:
      required: false

  - type: textarea
    id: user-benefit
    attributes:
      label: User Benefit
      description: How would this feature help Sofia residents?
      placeholder: |
        - Proactive health protection for vulnerable groups
        - Informed decisions about outdoor activities and exercise
        - Increased awareness of environmental issues
        - Better planning for daily commutes and activities
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Impact
      description: How important is this feature?
      options:
        - Critical - Blocks essential functionality
        - High - Significantly improves user experience
        - Medium - Nice to have, moderate impact
        - Low - Minor improvement
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes (Optional)
      description: Technical considerations, API requirements, or implementation suggestions
      placeholder: |
        - Backend: Add scheduled task to check air quality API
        - Database: Store user notification preferences (threshold values)
        - Frontend: Add settings screen for threshold configuration
        - Push: Use existing Expo notification infrastructure
        - Consider rate limiting to avoid notification spam
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: Attach designs, mockups, screenshots from other apps, or visual examples
      placeholder: Drag and drop images here
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Similar feature exists in app X
        - This was requested by multiple users in discussion Y
        - Related to existing issue #123
    validations:
      required: false
