name: 🌍 Translation Issue
description: Report missing, incorrect, or unclear translations
title: '[Translation]: '
labels: ['translation', 'i18n', 'needs-triage']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve translations! Your Sofia strives to be accessible to all Sofia residents in both Bulgarian and English.

  - type: textarea
    id: issue
    attributes:
      label: What's Wrong?
      description: Explain the issue with the current translation
      placeholder: |
        The phrase "лошо" is too informal. For a civic app, "незадоволително" or "нездравословно" would be more appropriate and clearer about health implications.
    validations:
      required: true

  - type: textarea
    id: suggested
    attributes:
      label: Suggested Translation Improvement
      description: Provide the corrected or improved translation
      placeholder: |
        Suggested text: "Качеството на въздуха е нездравословно!"

        This is more formal and clearly indicates health concerns, which is important for a civic notification.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: When/where does this text appear? Why is the suggested translation better?
      placeholder: |
        This text appears in push notifications when air quality exceeds threshold. Users need to immediately understand the severity, so formal, clear language is essential.
    validations:
      required: false
