import {StyleSheet} from 'react-native'
import {colors, fonts, fontSizes, radius, spacing} from '@/styles/tokens'

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface2,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: fontSizes.body,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.regular,
    color: colors.error,
    marginTop: 4,
  },
  retryButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: colors.surface,
    fontSize: fontSizes.body,
    fontFamily: fonts.semiBold,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    flex: 1,
    fontSize: 18,
    fontFamily: fonts.semiBold,
    color: colors.textPrimary,
    marginLeft: 12,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerButton: {
    padding: 8,
  },
  saveButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
  },
  scrollView: {
    flex: 1,
  },
  statusContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  statusText: {
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.semiBold,
  },
  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  categoryText: {
    fontSize: fontSizes.bodySm,
    color: colors.textSecondary,
    fontFamily: fonts.medium,
  },
  title: {
    fontSize: fontSizes.h2,
    fontFamily: fonts.bold,
    color: colors.textPrimary,
    paddingHorizontal: 16,
    marginTop: 16,
    lineHeight: 32,
  },
  imagesContainer: {
    flexDirection: 'row',
    gap: 12,
    paddingRight: 16,
  },
  image: {
    width: 200,
    height: 150,
    borderRadius: 12,
    backgroundColor: colors.surface2,
  },
  descriptionText: {
    fontSize: fontSizes.body,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
    lineHeight: 24,
  },
  section: {
    paddingHorizontal: 16,
    marginTop: 4,
  },
  sectionLabel: {
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.semiBold,
    color: colors.textSecondary,
    marginBottom: 8,
  },
  input: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: fontSizes.body,
    fontFamily: fonts.regular,
    color: colors.textPrimary,
  },
  inputError: {
    borderColor: colors.error,
  },
  textArea: {
    minHeight: 100,
    paddingTop: 12,
  },
  stateTagsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  stateTag: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  stateTagText: {
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.semiBold,
    color: colors.textSecondary,
  },
  stateTagTextSelected: {
    color: colors.surface,
  },
  metaText: {
    paddingLeft: 4,
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.regular,
    color: colors.textSecondary,
  },
  createMissionButton: {
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  createMissionButtonText: {
    color: colors.surface,
    fontSize: fontSizes.caption,
    fontFamily: fonts.semiBold,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xl,
  },
  modalSheet: {
    flex: 1,
    backgroundColor: colors.surface2,
    borderRadius: radius.xl,
    paddingTop: spacing.md,
    overflow: 'hidden',
  },
  modalHeader: {
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    color: colors.textPrimary,
    fontSize: fontSizes.h3,
    fontFamily: fonts.bold,
  },
  modalSubtitle: {
    color: colors.textSecondary,
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.regular,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.xs,
  },
  modalCloseButton: {
    padding: 8,
  },
  adminNotesContainer: {
    flexDirection: 'row',
    gap: 12,
    padding: 12,
    backgroundColor: colors.primaryTint,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
  },
  adminNotesText: {
    flex: 1,
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.regular,
    color: colors.primary,
    lineHeight: 20,
  },
  infoBox: {
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 32,
    padding: 16,
    backgroundColor: '#FEF3C7',
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#F59E0B',
  },
  infoText: {
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.regular,
    color: '#92400E',
    lineHeight: 20,
  },
  photoWrapper: {
    position: 'relative',
  },
  deletePhotoButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: colors.error,
    borderRadius: 12,
    padding: 4,
  },
  photoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.primary,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  photoButtonText: {
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.semiBold,
    color: colors.primary,
  },
  lifecycleBanner: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 4,
    padding: 16,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  lifecycleStepsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  lifecycleStep: {
    flex: 1,
    alignItems: 'center',
  },
  lifecycleStepCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
  },
  lifecycleStepCircleActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  lifecycleStepCircleDone: {
    borderColor: colors.success,
    backgroundColor: colors.success,
  },
  lifecycleStepCircleRejected: {
    borderColor: colors.error,
    backgroundColor: colors.error,
  },
  lifecycleStepLabel: {
    fontSize: fontSizes.caption,
    fontFamily: fonts.medium,
    color: colors.textMuted,
    textAlign: 'center',
  },
  lifecycleStepLabelActive: {
    color: colors.primary,
    fontFamily: fonts.semiBold,
  },
  lifecycleStepLabelDone: {
    color: colors.success,
    fontFamily: fonts.semiBold,
  },
  lifecycleStepLabelRejected: {
    color: colors.error,
    fontFamily: fonts.semiBold,
  },
  lifecycleConnector: {
    height: 2,
    flex: 1,
    backgroundColor: colors.border,
    marginBottom: 22,
  },
  lifecycleConnectorActive: {
    backgroundColor: colors.success,
  },
  lifecycleMessage: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 12,
    borderRadius: radius.md,
  },
  lifecycleMessagePending: {
    backgroundColor: colors.surface2,
  },
  lifecycleMessageInProgress: {
    backgroundColor: colors.infoLight,
  },
  lifecycleMessageResolved: {
    backgroundColor: colors.successLight,
  },
  lifecycleMessageRejected: {
    backgroundColor: colors.errorLight,
  },
  lifecycleMessageText: {
    flex: 1,
    fontSize: fontSizes.bodySm,
    fontFamily: fonts.regular,
    lineHeight: 20,
  },
  lifecycleMessageTextPending: {
    color: colors.textSecondary,
  },
  lifecycleMessageTextInProgress: {
    color: colors.info,
  },
  lifecycleMessageTextResolved: {
    color: colors.success,
  },
  lifecycleMessageTextRejected: {
    color: colors.error,
  },
})
